# Generated by Django 4.0.4 on 2022-05-08 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=15, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('shelf_count', models.IntegerField(default=1, verbose_name='Количество полок')),
                ('section_count', models.IntegerField(default=1, verbose_name='Количество секций')),
                ('row_count', models.IntegerField(default=1, verbose_name='Количество рядов')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('row', models.CharField(choices=[('Первый', 'Первый'), ('Второй', 'Второй'), ('Третий', 'Третий'), ('Четвертый', 'Четвертый')], default='', max_length=100, verbose_name='Ряд')),
                ('is_current', models.BooleanField(default=False, verbose_name='Является текущей')),
                ('bookcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='catalog.bookcase', verbose_name='Книжный шкаф')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('pages', models.IntegerField(blank=True, default='', null=True, verbose_name='Количество страниц')),
                ('year_of_publication', models.CharField(blank=True, default='', max_length=10, verbose_name='Год издания')),
                ('language', models.CharField(blank=True, default='', max_length=50, verbose_name='Язык')),
                ('ISBN', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ISBN')),
                ('type_of_cover', models.CharField(blank=True, default='', max_length=25, verbose_name='Тип обложки')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитана')),
                ('parse_isbn', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Поиск по ISBN')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Автор')),
                ('bookcase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.bookcase', verbose_name='Книжный шкаф')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.shelf', verbose_name='Полка')),
            ],
        ),
    ]
