# Generated by Django 4.0.4 on 2022-05-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookcase', verbose_name='Книжный шкаф'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.shelf', verbose_name='Полка'),
            preserve_default=False,
        ),
    ]
