# Generated by Django 4.0.4 on 2022-05-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_shelf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
