# Generated by Django 4.0.4 on 2022-05-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_author',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Новый автор'),
        ),
    ]
