# Generated by Django 4.0.4 on 2022-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_new_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='new_author',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Новый автор'),
        ),
    ]
