# Generated by Django 4.0.4 on 2022-05-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='textarea',
            field=models.TextField(blank=True, default=''),
        ),
    ]
