# Generated by Django 4.0.4 on 2022-05-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_textarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='textarea',
            new_name='annotation',
        ),
    ]
