# Generated by Django 4.0.4 on 2022-05-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='owner',
        ),
    ]
