# Generated by Django 4.0.4 on 2022-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_book_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='new_author',
            field=models.CharField(max_length=150, verbose_name='Новый автор'),
        ),
    ]
