# Generated by Django 4.0.4 on 2022-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_new_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='new_author',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Новый автор'),
        ),
    ]
